### ISSUE TITLE
"No shape named `{whatever}` is known" with the annotate macro on overleaf.

### ISSUE THREAD

**Issue by johnabs** [st--/annotate-equations#10] opened 2022-12-12 19:01 UTC
To whom it may concern,

I attempted to load this package on Overleaf and run the examples, but the annotate functions didn't work correctly, apparently because they couldn't find the nodes in the equation.

If you need any further information (e.g. my preamble) to replicate this result, please let me know. However, I noticed it does work with a test project, when I pull in the dependencies from the .sty file. Any reason why that would work?

Thanks for your help, I greatly appreciate it.

Best,
John

**Comment by GabLoyer** [comment] 2022-12-20 14:55
I had relativity the same error on my part too, but resolved it by adding the following tikz library in my latex file: 
~~~tex
\usetikzlibrary{babel}
~~~
It seems the library is depending on an older version of latex than what is on Overleaf ?
I followed this [thread](https://tex.stackexchange.com/questions/344671/package-tikz-error).

**Comment by st--** [comment] 2023-02-08 12:52
Thanks @GabLoyer for suggesting a workaround! Is this an issue with the `annotate-equations` package (i.e. something that ought to get fixed in its code), or simply an interaction between `babel` and `tikz` (and it's out of scope, or at most we can mention it in the docs)?

**Comment by st--** [comment] 2023-02-14 15:43
@johnabs I tried out compiling the annotate-equation.tex package documentation within Overleaf, and it all seems to work fine for me. So if you could provide instructions for how to reproduce your issue, that would indeed be helpful in trying to determine what's going on! (See "[minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)" on Stackoverflow)

**Comment by st--** [comment] 2023-07-18 14:18
Closing this as I can't reproduce it. Feel free to reopen with a reproducible example.

**Closed as not planned by st--** 2023-07-18 14:18 UTC
Labels: can't reproduce
