### ISSUE TITLE
Can't work well when using "xe->bib->xe->xe" recipe in a beamer project.

### ISSUE THREAD

**Issue by hjnnjh** [st--/annotate-equations#21] opened 2023-09-19 12:06 UTC
When I need to compile references and citations in a beamer project using `Bibtex` no matter how many times I compile with`xelatex`, the comments don't get put in the right place. I've tried "xe->bib->xe->xe", "xe->bib->xe->xe->xe->xe" etc.

**Comment by st--** [comment] 2023-09-20 06:47
Hi, does it work without bibtex? I've not worked with xelatex myself, so it _might_ be that it's not actually compatible, but hard to say without a concrete example. Can you prepare a minimal reproducible example that demonstrates the issue?

**Comment by hjnnjh** [comment] 2023-09-20 07:52
> Hi, does it work without bibtex? I've not worked with xelatex myself, so it _might_ be that it's not actually compatible, but hard to say without a concrete example. Can you prepare a minimal reproducible example that demonstrates the issue?

[This](https://github.com/hjnnjh/annotate-equations-example) is one of my beamer projects. If you don't add references, compile four times with`xelatex` and everything works fine. If you add references, that is, use `xe->bib->xe->xe` compile chain, there will be a problem.

**Comment by st--** [comment] 2023-09-23 11:54
I've downloaded your example project and it seems to compile fine for me. I use `latexmk` to let it figure out which commands to run how often, using the following command-line:
```bash
latexmk -xelatex -shell-escape slide
```
(the `-shell-escape` seems to be needed by the `minted` package).

The only change I had to make to your file is comment out settings related to fonts I don't have,
```diff
-\setsansfont{PingFang SC} % make sure your system has this font
-\setCJKsansfont{STSongti-SC-Bold} % Chinese font, make sure your system has this font
```
I'm going to close this issue for now as I can't reproduce the issue.

**Closed as completed by st--** 2023-09-23 11:54 UTC
Labels: can't reproduce

**Comment by hjnnjh** [comment] 2023-09-25 08:46
> I've downloaded your example project and it seems to compile fine for me. I use `latexmk` to let it figure out which commands to run how often, using the following command-line:
> 
> ```shell
> latexmk -xelatex -shell-escape slide
> ```
> 
> (the `-shell-escape` seems to be needed by the `minted` package).
> 
> The only change I had to make to your file is comment out settings related to fonts I don't have,
> 
> ```diff
> -\setsansfont{PingFang SC} % make sure your system has this font
> -\setCJKsansfont{STSongti-SC-Bold} % Chinese font, make sure your system has this font
> ```
> 
> I'm going to close this issue for now as I can't reproduce the issue.

Why did I get the different result by running the same command :(. My texlive version is `texlive 2023` and `Latexmk` version is `John Collins, 4 Apr. 2023. Version 4.80.`
```
Latexmk: Maximum runs of xelatex reached without getting stable files
Latexmk: Summary of warnings from last run of *latex:
  =====Latex reported missing or unavailable character(s).
=====See log file for details.
Latexmk: ====List of undefined refs and citations:
  Missing character: There is no ﬁ ("FB01) in font ec-lmss10!
Latexmk: Errors, so I did not complete making targets
----------------------
This message may duplicate earlier message.
Latexmk: Failure in processing file 'slide':
   'xelatex' needed too many passes
----------------------

Latexmk: If appropriate, the -f option can be used to get latexmk
  to try to force complete processing.
```

**Comment by hjnnjh** [comment] 2023-09-25 08:50
> I've downloaded your example project and it seems to compile fine for me. I use `latexmk` to let it figure out which commands to run how often, using the following command-line:
> 
> ```shell
> latexmk -xelatex -shell-escape slide
> ```
> 
> (the `-shell-escape` seems to be needed by the `minted` package).
> 
> The only change I had to make to your file is comment out settings related to fonts I don't have,
> 
> ```diff
> -\setsansfont{PingFang SC} % make sure your system has this font
> -\setCJKsansfont{STSongti-SC-Bold} % Chinese font, make sure your system has this font
> ```
> 
> I'm going to close this issue for now as I can't reproduce the issue.

I compiled this project in VSCode, and the corresponding setting is as follows:
```
{
      "name": "latexmk",
      "command": "latexmk",
      "args": [
        "-xelatex",
        "-synctex=1",
        "-shell-escape",
        "-interaction=nonstopmode",
        "-file-line-error",
        "%DOC%"
      ]
    }
```

**Comment by hjnnjh** [comment] 2023-09-25 08:51
Really feel confused :(

**Comment by st--** [comment] 2023-10-18 20:19
@hjnnjh what happens if you also comment out the two packages I had to comment out ?

**Comment by hjnnjh** [comment] 2023-10-23 02:45
> @hjnnjh what happens if you also comment out the two packages I had to comment out ?

if I compile it with `.bib` file, which means:
```diff
-\setsansfont{PingFang SC} % make sure your system has this font
-\setCJKsansfont{STSongti-SC-Bold} % Chinese font, make sure your system has this font

+\begin{frame}[allowframebreaks]{References}
+     \bibliography{reference}
+     \bibliographystyle{informs2014}
+\end{frame}
...

+Model only one kind of customer digital footprints—news consumption\citep{trusov2016crumbs};
```
Using `latexmk`:
![image](https://github.com/st--/annotate-equations/assets/37699150/b3766823-5403-4e23-8370-e8a179221d88)

Using `xe->bib->xe->xe`:
![image](https://github.com/st--/annotate-equations/assets/37699150/48a2b031-8756-42a3-8cfb-e8fa4ca56f13)

What happened?

**Comment by hjnnjh** [comment] 2023-10-26 06:02
> @hjnnjh what happens if you also comment out the two packages I had to comment out ?

I have solved this problem, I have to add "-f" option when compiling it with latexmk. Sry to bother you.
